Add jei and tom simple storage support
ODDCraft/RoughlyEnoughCharacters pull request #11
Opened 2022-07-19 13:42 UTC by vfyjxf

2022-07-19 14:56 UTC, oott123 requested changes

2022-07-19 14:56 UTC, oott123 commented on build.gradle
> +    modImplementation "mezz.jei:jei-${minecraft_version}-fabric:10.1.0.228"
请移除对 JEI 的依赖……

2022-07-19 14:56 UTC, oott123 commented on src/main/java/com/oott123/rechars/mixins/MixinJeiSearch.java
> +@Mixin(value = ElementPrefixParser.class)
移除依赖之后这里改用字符串匹配对应 class 即可

2022-07-19 14:58 UTC, vfyjxf commented on build.gradle
> +    modImplementation "mezz.jei:jei-${minecraft_version}-fabric:10.1.0.228"
> 请移除对 JEI 的依赖……
但对jei的兼容是通过继承GeneralizedSuffixTree和重写方法来替换的逻辑，清除的话无法通过编译吧。

2022-07-20 01:52 UTC, oott123 commented on build.gradle
> +    modImplementation "mezz.jei:jei-${minecraft_version}-fabric:10.1.0.228"
说得也很有道理，那这个地方有点难搞，你这边依赖了 JEI 的话整个 mod 都要依赖 JEI 了。那是不是应该 mixin `GeneralizedSuffixTree` 呢？在这个类里面加一个字段用来存 pinin 的 `TreeSearcher`，然后 mixin 原来的 put 和 search 方法。

2022-07-20 02:42 UTC, vfyjxf commented on build.gradle
> +    modImplementation "mezz.jei:jei-${minecraft_version}-fabric:10.1.0.228"
> 说得也很有道理，那这个地方有点难搞，你这边依赖了 JEI 的话整个 mod 都要依赖 JEI 了。那是不是应该 mixin `GeneralizedSuffixTree` 呢？在这个类里面加一个字段用来存 pinin 的 `TreeSearcher`，然后 mixin 原来的 put 和 search 方法。

其实我不太理解为什么这样子就成了整个mod依赖jei了，这里应该只是用于编译，还是说因为要jei才能编译就所以说"依赖"jei。这样子实际测试中没有jei mixin也依旧正常工作。至于mixin GeneralizedSuffixTree类，jei其他的搜索逻辑也是基于GeneralizedSuffixTree类的（如mod名搜索，tag搜索）我认为直接mixn GeneralizedSuffixTree可能会让这些场景的搜索出现性能问题（因为拼音搜索肯定比原有的实现慢一些），所以我个人并不想 miixn GeneralizedSuffixTree类。

2022-07-20 02:48 UTC, oott123 commented on build.gradle
> +    modImplementation "mezz.jei:jei-${minecraft_version}-fabric:10.1.0.228"
> 其实我不太理解为什么这样子就成了整个mod依赖jei了

因为看起来 mod 用到了 JEI 的代码，我不太懂 java 所以这里可能说得不对。

如果没有 JEI 的时候也能工作，那我没有什么问题。

2022-07-20 02:53 UTC, vfyjxf commented on build.gradle
> +    modImplementation "mezz.jei:jei-${minecraft_version}-fabric:10.1.0.228"
> 如果没有 JEI 的时候也能工作，那我没有什么问题。

我在实际测试中没有jei其他mod的兼容也可以工作。

2022-07-20 03:18 UTC, oott123 approved these changes

2022-07-20 03:18 UTC, merged